# Generated by Django 5.1.1 on 2024-09-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientapp', '0002_patient_delete_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('disease', models.CharField(max_length=125)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
