# Generated by Django 5.1.1 on 2024-09-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tatient',
            new_name='Patient',
        ),
    ]
